### ISSUE TITLE
tutorial version

### ISSUE THREAD

**Issue by ardelgadillov** [IIT-EnergySystemModels/openTEPES-tutorial#1]
I think the openTepes tutorial jupyter notebooks are not updated to the latest openTepes version. Input data files have different structure in new openTepes version

**Comment by erikfilias** [comment]
Hi @ardelgadillov,

Indeed, the CSV files were outdated, but it was updated nine days ago.
And the tutorial is currently working:
![image](https://user-images.githubusercontent.com/8010477/181493262-39aadda7-78e8-47d4-8331-65da71ebb8ad.png)

If there will be another issue, please let us know.

[openTEPES-Tutorial](https://mybinder.org/v2/gh/IIT-EnergySystemModels/openTEPES-tutorial/HEAD)
