### ISSUE TITLE
Binder not working

### ISSUE THREAD

**Issue by pgoiporia** [IIT-EnergySystemModels/openTEPES-tutorial#2]
I was trying to run the 9n tutorial, but the binder environment fails to build.

**Comment by erikfilias** [comment]
Thanks, @pgoiporia, for reporting it. 
I think I solved the issue.
Please try it again and let me know if it builds well.

**Comment by pgoiporia** [comment]
That fixed it! There are a couple of other errors I'll document in a separate issue (related to the notebooks, not the binder instance). The actual binder container only has 2GB of memory. Any chance this could be increased? It crashes pretty quickly.

**Comment by erikfilias** [comment]
Great, thanks.
Unfortunately, we didn't explore increasing memory years ago.
I'll try to take a look, but I don't promise the increase.
